apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloop-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashloop-example
  template:
    metadata:
      labels:
        app: crashloop-example
    spec:
      containers:
      - name: failing-container
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "This is a deliberate failure."
          exit 1